Dz1
lada-nikiforova/2024-2-VK-EDU-Frontend-L-Nikiforova pull request #1
Opened 2024-09-20 12:49 UTC by lada-nikiforova

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Доделана функция в файле correctSentence.js
* Написаны функции в файлах convertBytesToHuman.js, nonUniqueElements.js
* Написаны тесты в файле convertBytesToHuman.test.js

2024-09-22 07:31 UTC, sh4rkizz requested changes

2024-09-22 07:31 UTC, sh4rkizz commented on convertBytesToHuman.js
> +  }
Тесты пройдены, но решение сложно масштабировать

Подумай, можешь ли ты применить циклы [или математику] для решения задачи для **любого** размера массива `sizes`, например если добавятся петабайты, эксабайты и так далее

2024-09-22 07:31 UTC, sh4rkizz commented on convertBytesToHuman.js
> +  if (typeof bytes !== 'number' | bytes < 0 | isNaN(bytes)){
в js логический оператор ИЛИ это `||`, не стоит использовать побитовое ИЛИ `|`

Поведение может быть непредсказуемым для небулевых значений, стоит сделать использование корректного оператора привычкой

<img width="405" alt="изображение" src="https://github.com/user-attachments/assets/7c6cf52b-7213-4de8-b6b6-fe5010ef6576">

2024-09-22 07:31 UTC, sh4rkizz commented on nonUniqueElements.js
> +}
Решение интересное, но алгоритмическая сложность `O(n^2)` это не очень хорошо
Подумай, сможешь ли ты применить **объекты** или **Map** для хранения `count`

Улучшатся скорость работы и читаемость кода

2024-09-22 07:31 UTC, sh4rkizz commented on convertBytesToHuman.test.js
> +});
Давай дополним набор тестов значением `Infinity` и посмотрим пройдет ли этот тест

2024-09-22 07:37 UTC, sh4rkizz commented
Следует также добавить преподов в `asingee`/`reviewers`, согласно инструкции сдачи домашек

2024-09-23 10:56 UTC, sh4rkizz approved these changes
LGTM

2024-09-25 20:49 UTC, martinkomitsky approved these changes
12!

2024-09-25 20:49 UTC, merged