Dz10
lada-nikiforova/2024-2-VK-EDU-Frontend-L-Nikiforova pull request #10
Opened 2024-12-08 12:47 UTC by lada-nikiforova

# Домашнее задание №10

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Добавлен список пользователей в модальном окне при создании чата
*
*

2024-12-08 14:06 UTC, sh4rkizz requested changes
+ к тому что отписал в личке

2024-12-08 14:06 UTC, sh4rkizz commented on react-chat/src/components/Modal/Modal.jsx
>          const value = event.target.value.trim();
Я понял, что некорректно делать `.trim();` в onChange [надо при сохранении / попытке сохранить]
Мешает создавать название чата с пробелом [можно назвать только в одно слово]

2024-12-08 14:06 UTC, sh4rkizz commented on react-chat/src/api/apiChat.js
> +        "is_private": flag,
можно прям здесь передавать `"is_private": id.length > 1`, не нужно ifelse + переменную для этого

2024-12-08 14:06 UTC, sh4rkizz commented on react-chat/src/api/apiUser.js
> +    const { data } = await apiClient.get(`/api/user/${id}`);
таких мест несколько 

нужно добавлять закрывающий `/` в конец урла для запроса 
[даже когда есть GET-параметры - перед ?]

если этого не сделать будут приходить 301ые коды

<img width="554" alt="изображение" src="https://github.com/user-attachments/assets/fcebc590-57ee-4b79-a7b6-f86ac778c1db">

2024-12-08 14:12 UTC, sh4rkizz commented on react-chat/src/components/Modal/Modal.jsx
> +    const fetchUsers = async () => {
Стоит использовать еще `lodash.debounce` с задержкой в `300-500` мс, чтобы не каждое нажатие символа приводило к запросу на бекенд, а только когда пользователь перестает вводить символы

https://www.npmjs.com/package/lodash.debounce

2024-12-16 21:42 UTC, sh4rkizz approved these changes
lgtm !

2024-12-17 10:51 UTC, merged

2024-12-17 10:51 UTC, martinkomitsky commented
7