dz4
lada-nikiforova/2024-2-VK-EDU-Frontend-L-Nikiforova pull request #4
Opened 2024-10-11 23:09 UTC by lada-nikiforova

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Возможность создавать чаты без хардкода
* Созданные чаты стали кликабельными, с возможностью писать в них
* Анимированные кнопки с помощью css

2024-10-13 08:33 UTC, sh4rkizz commented
Заметил какой-то странный текст с данными из localstorage

<img width="1440" alt="изображение" src="https://github.com/user-attachments/assets/26b7c5aa-12e5-4add-bd62-ed8245c2b7d3">

2024-10-13 08:35 UTC, sh4rkizz requested changes
В рамках задания все выполнено отлично, также вижу доработки, которые запрашивал

Давай поправим и будет вообще супер

2024-10-13 08:35 UTC, sh4rkizz commented on simple-chat/src/pages.html
>          <title>Document</title>
Давай сделаем контекстный title, говорящий о том, что действительно на странице расположено

2024-10-13 08:35 UTC, sh4rkizz commented on simple-chat/src/pages.html
> +            <div class="overlay hidden"></div>
Предлагаю докинуть webkit-clamp и для пользователя

<img width="1440" alt="изображение" src="https://github.com/user-attachments/assets/35496ffa-77fa-483f-91c2-9da24c53d942">

2024-10-13 08:35 UTC, sh4rkizz commented on simple-chat/src/pages.html
> +            <div class="overlay hidden"></div>
Такое заведение так же ломает шапку самого чата и автора-отправителя
<img width="1439" alt="изображение" src="https://github.com/user-attachments/assets/03f0c2e1-511c-4bd2-bd5c-e0a81bd899fa">

2024-10-13 08:35 UTC, sh4rkizz commented on simple-chat/webpack.config.js
>              chunks: ['index', 'openChat']
Предложение по UX, передвинуть боковую менюшную колонку вниз 
[сделать футером как сделано в ВК и youtube]

Также [лично мое мнение] стоит это меню отображать только на странице со списком чатов, чтобы не загромождать пространство

На мобильных устройствах очень маленькое горизонтальное контентное пространство, думаю не стоит его уменьшать дополнительными колонками с меню 
<img width="127" alt="изображение" src="https://github.com/user-attachments/assets/105ec145-24ea-47f2-b051-5c5c07846766">


<img width="127" alt="изображение" src="https://github.com/user-attachments/assets/467ec028-49a9-4108-9153-c7e1a70e6189">

2024-10-14 18:16 UTC, sh4rkizz approved these changes
огонь!

2024-10-19 12:23 UTC, martinkomitsky commented
12!

2024-10-19 12:23 UTC, merged