Dz5
lada-nikiforova/2024-2-VK-EDU-Frontend-L-Nikiforova pull request #5
Opened 2024-10-21 12:45 UTC by lada-nikiforova

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Создан проект на основе vite react
* Переписаны компоненты. Восстановлены стили и функциональность
* Обновление параметров для gh-pages

2024-10-21 20:55 UTC, sh4rkizz requested changes
Хорошая работа, в целом все хорошо, предлагаю стилистически довести до идеала

2024-10-21 20:55 UTC, sh4rkizz commented on react-chat/src/main.jsx
> +// import { StrictMode } from 'react'
принципиальный момент, файлы корректнее называть index.*, поскольку именно они являются отправной точкой приложений

2024-10-21 20:55 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
> +        localStorage.setItem('activePerson', name);
Ключи localStorage корректнее вынести в отдельный файлик с константами
[например `constants.js`]

2024-10-21 20:55 UTC, sh4rkizz commented on react-chat/index.html
> +</html>
Предлагаю убрать автокомплит поля ввода тут
<img width="830" alt="изображение" src="https://github.com/user-attachments/assets/6735a618-ca7d-4ac1-9f11-eb191e97b9fb">

И тут
<img width="569" alt="изображение" src="https://github.com/user-attachments/assets/3ec34ef3-6c3e-4225-81e4-fe05cc0cea2d">

2024-10-21 20:55 UTC, sh4rkizz commented on react-chat/src/components/Modal/Modal.jsx
> +                    <input className="form-text" name="text" placeholder="Введите имя собеседника" type="text" value={namePerson} onChange={(e) => setNamePerson(e.target.value)} required/>
Стоит в метод обработки докинуть trim(), чтобы нельзя было создавать пробелами чатики

<img width="564" alt="изображение" src="https://github.com/user-attachments/assets/a1285ef3-c56e-48cd-823e-dbcecb354903">

2024-10-21 20:55 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +  const [currentPage, setCurrentPage] = useState('chatList');
Кажется немного странным, что при обновлении страницы [если я нахожусь в переписке] меня возвращает на страницу списка чатов

Возможно нужно парсить URL в useEffect, чтобы отрендерить нужную страницу

2024-10-21 20:55 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +      {currentPage === 'chatList' && <PageChatList onBack={goToChat} />}
Предлагаю сделать контейнеры побольше, на десктопе мало инфы влазит

<img width="831" alt="изображение" src="https://github.com/user-attachments/assets/f4af0bf8-afbc-4c86-975e-74dde237ff09">

<img width="975" alt="изображение" src="https://github.com/user-attachments/assets/93e87d54-af4c-4de5-9a22-24ef32fb5101">

2024-10-21 20:55 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +      {currentPage === 'chatList' && <PageChatList onBack={goToChat} />}
Также хочется поправленный горизонтальный скролл при длинном сообещнии собеседника
<img width="1029" alt="изображение" src="https://github.com/user-attachments/assets/d5c7f834-48a2-4063-a057-cc86d1c8a68d">

2024-10-21 20:55 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +      {currentPage === 'chatList' && <PageChatList onBack={goToChat} />}
название чата немного срезается снизу [видно по букве g]
<img width="182" alt="изображение" src="https://github.com/user-attachments/assets/48614335-762c-408d-863a-438904beba07">

2024-10-21 20:56 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +      {currentPage === 'chatList' && <PageChatList onBack={goToChat} />}
Кнопочка тоже слегка кривовата 

<img width="307" alt="изображение" src="https://github.com/user-attachments/assets/a0a125a5-047e-45a9-9864-763439ea7c3c">

2024-10-23 16:57 UTC, sh4rkizz approved these changes
lgtm! огонь

2024-10-23 18:32 UTC, merged

2024-10-23 18:33 UTC, martinkomitsky commented
12!