Dz6
lada-nikiforova/2024-2-VK-EDU-Frontend-L-Nikiforova pull request #6
Opened 2024-10-26 15:39 UTC by lada-nikiforova

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Настроены переходы на страницы с помощью react-router 
* Добавлена страница профиля (переход на нее с помощью кнопки с иконкой настроек)

2024-10-27 00:37 UTC, sh4rkizz requested changes

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +        localStorage.setItem(profile, JSON.stringify(newDate));
Хотелось бы какое-нибудь сообщение об успешности
алерт / модалку / просто текст на странице, появляющийся на несколько секунд

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +        localStorage.setItem(profile, JSON.stringify(newDate));
Давай ради опыта сделаем `fullname` и `username` обязательным полем
- покажем красную звездочку у лейбла поля
- при попытке сохранения проводить фронтовую валидацию:
  - обработка ошибка при пустоте поля ["Это поле обязательно"]
  - клиентская валидация длины полей (по стандарту 255) ["Длина этого поля не может превышать 255 символов (сейчас N)"] 
  - если хочешь, можно прикрутить проверку с использованием `regex`, например, чтобы `username` состоял только из символов латинского алфавита

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +            <HeaderChatList title='Страница профиля' rightIcon={CheckIcon} onRightIconClick={saveDate}/>
Какая-то незаметная кнопочка затесалась здесь
<img width="306" alt="изображение" src="https://github.com/user-attachments/assets/de5fc3b1-69b4-4303-98a1-84bf8b412ae1">

Мое предложение, поменять подход к хедеру, разбив его на хедер для каждой отдельной страницы
`rightIcon, onRightIconClick, leftIcon, onLeftIconClick` - труднорасширяемый функционал

Лучше иметь несколько header компонентов, для каждой страницы - свой
Прикольно было бы увидеть такую реализацию

```
components /
    header /
        HeaderChatList.jsx
        HeaderChat.jsx
        HeaderProfile.jsx
        index.jsx - файл внутри которого будет прописано:
                export { HeaderProfile } from "./HeaderProfile.jsx"
                export { HeaderChatList } from "./HeaderChatList.jsx"
                export { HeaderChat } from "./HeaderChat.jsx"
```

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +                    <InputProfile name="username" rows='1' placeholder="Введите имя пользователя"  value={userName} onChange={(e) => setUserName(e.target.value)}/>
Более корректно использовать здесь однострочные `<input>` элементы, вместо `<textarea>`
Такие поля как правило имеют бекендовое ограничение в `255 символов`

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +    </HashRouter>
Поскольку у нас теперь есть роутинг, думаю, было при классно иметь отображение активной страницы в футере

<img width="833" alt="изображение" src="https://github.com/user-attachments/assets/fd24ee7b-fde6-45ec-b9b1-44db8aca5b35">

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/components/ChatList/ChatList.jsx
> +                <button key={button.id} id={button.id} className='container-button-chat' onClick={()=>{onChatClick(button.id, button.name);}}>
Кажется что с внерением роутинга это должна быть ссылка `<Link to="/chat/<id>">`

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/components/Footer/Footer.jsx
> +            </Link>
Здесь что-то одно стоит выбрать либо `Link` либо `button`
Корректнее будет использовать только Link

[сейчас при навигации табом фокусируются эти элементы по два раза]

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/components/Header/Header.jsx
> +            </Link>
аналогично про выбор Link/button

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +        </div>
из-за стилизации бывает уползает скроллбар [при ховере]
<img width="160" alt="изображение" src="https://github.com/user-attachments/assets/01d5476c-dfff-4847-875d-e55f3b2b7f4c">

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/components/ChatList/ChatList.jsx
> +                <button key={button.id} id={button.id} className='container-button-chat' onClick={()=>{onChatClick(button.id, button.name);}}>
На мобилке страничка профиля выглядит немного поломанной

<img width="430" alt="изображение" src="https://github.com/user-attachments/assets/f9d0ed6e-15e2-4974-9cf9-53a3024db9c8">

2024-10-27 00:37 UTC, sh4rkizz commented on react-chat/src/components/ChatList/ChatList.jsx
> +                <button key={button.id} id={button.id} className='container-button-chat' onClick={()=>{onChatClick(button.id, button.name);}}>
Если сохранять поля без изменений в консольку будут падать ошибки [и сохранение других полей, которые заполнены, происходить не будет]
<img width="617" alt="изображение" src="https://github.com/user-attachments/assets/ff25cac5-3d35-4d8a-ba69-f424683935e2">

2024-10-29 13:45 UTC, sh4rkizz requested changes
пара замечаний, поправишь - будет очень круто

2024-10-29 13:45 UTC, sh4rkizz commented on react-chat/src/components/ChatList/ChatList.jsx
> +                <Link to= {`/chat/${button.id}`} key={button.id} id={button.id} className='container-button-chat' onClick={()=>{onChatClick(button.id, button.name);}}>
`onClick={()=>{onChatClick(button.id, button.name);}}` теперь не нужен, потому что переход по ссылке осуществляется

2024-10-29 13:45 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +                    <InputProfile name="surname" placeholder="Введите вашу фамилию" value={surname} onChange={(e) => setSurname(e.target.value)} error={error.surname} errorMessage="Введите вашу фамил
лучше нейминг оставить как на бэке - first_name, last_name

2024-10-29 13:45 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +                    <InputProfile name="surname" placeholder="Введите вашу фамилию" value={surname} onChange={(e) => setSurname(e.target.value)} error={error.surname} errorMessage="Введите вашу фамил
и ошибочки лучше делать красные + небольшой отступ над текстом

![изображение](https://github.com/user-attachments/assets/919922fb-ff2e-4af0-900b-70e65ab5917f)

2024-10-29 13:45 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +                    <InputProfile name="surname" placeholder="Введите вашу фамилию" value={surname} onChange={(e) => setSurname(e.target.value)} error={error.surname} errorMessage="Введите вашу фамил
Из-за padding: 10px при клике на элемент менюшки он сдвигается, нужно какое-то другое решение

<img width="277" alt="изображение" src="https://github.com/user-attachments/assets/8408da4d-2680-4ba9-bfa7-b40922a2c1ea">
<img width="174" alt="изображение" src="https://github.com/user-attachments/assets/2e5cc08a-de63-4d6f-b8f9-f74be3cea649">

2024-10-29 14:00 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +                    <InputProfile name="surname" placeholder="Введите вашу фамилию" value={surname} onChange={(e) => setSurname(e.target.value)} error={error.surname} errorMessage="Введите вашу фамил
мобилочка все еще подломана по ширине

<img width="396" alt="изображение" src="https://github.com/user-attachments/assets/a4cb154d-eb8b-4273-b4f0-fda8ada47c06">

2024-10-29 16:16 UTC, sh4rkizz approved these changes
lgtm

2024-10-31 06:27 UTC, HaseProgram approved these changes
Супер, 12!

2024-10-31 06:27 UTC, merged