dz7
lada-nikiforova/2024-2-VK-EDU-Frontend-L-Nikiforova pull request #7
Opened 2024-11-11 11:21 UTC by lada-nikiforova

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Основная логика была подключена к бекенду
* Реализованы две страницы; регистрация и вход
* Пока что создание чата только по айди пользователя и возможно создать только личную беседу

Пример отправки сообщений: https://cloud.mail.ru/public/ZXYi/XTheS2HT4
https://lada-nikiforova.github.io/2024-2-VK-EDU-Frontend-L-Nikiforova/

2024-11-12 18:09 UTC, sh4rkizz requested changes

2024-11-12 18:09 UTC, sh4rkizz commented on react-chat/src/api/apiChat.js
> +
кажется имя пользователя растягивает сообщение

![изображение](https://github.com/user-attachments/assets/f4574877-f3d0-4b29-a41e-255a29359af5)

2024-11-12 18:09 UTC, sh4rkizz commented on react-chat/src/api/apiChat.js
> +
Стоит сбрасывать ошибки, когда ввод в поле осуществляется

![изображение](https://github.com/user-attachments/assets/ae259e83-1be3-47f2-8de4-d621aabc1dd4)

2024-11-12 18:09 UTC, sh4rkizz commented on react-chat/src/api/apiChat.js
> +
Ошибка такая, будто сервер подорвался, хотя на деле всего-лишь занят такой ник)
Предлагаю ошибки POST/PATCH/UPDATE запросов выводить под полем красненьким [брать то, что возвращает сервер]

![изображение](https://github.com/user-attachments/assets/02af0efe-2ce8-4732-97e6-41b6c2241f9c)

![изображение](https://github.com/user-attachments/assets/021dcf1c-609e-4f39-aa26-c196a047f107)

2024-11-12 18:09 UTC, sh4rkizz commented on react-chat/src/api/apiChat.js
> +
Странным образом не обновляются данные профиля
Запрос-Ответ

![изображение](https://github.com/user-attachments/assets/738bc820-b591-4f27-9bb6-227a4f49a691)

![изображение](https://github.com/user-attachments/assets/1df69ee0-8bd6-4f28-9c0b-0447cdf7b735)

2024-11-12 18:09 UTC, sh4rkizz commented on react-chat/src/api/apiChat.js
> +
Я как пользователь не могу знать UUID других юзеров
[могу, но тогда я не обычный пользователь уже]

Стоит сделать выбор человека / нескольких людей, с кем хочешь создать чат
Для реализации этого есть возможность получить+пофильтровать список пользователей



![изображение](https://github.com/user-attachments/assets/2a48f027-f086-4db3-814c-4992245f2208)

2024-11-12 18:53 UTC, sh4rkizz commented on react-chat/src/api/apiChat.js
> +
нужно обработать на всех страницах

![изображение](https://github.com/user-attachments/assets/6fe89486-1676-40b8-8180-8c1638031dce)

2024-11-15 14:24 UTC, sh4rkizz commented on react-chat/src/components/Register/Register.jsx
> +    };
Можно немного упростить себе жизнь с обработкой ошибок и сбором данных
Потребуется всего 2 useState [вместо N], 1 handleChange [вместо N]

```
const [errors, setErrors] = useState({});
const [data, setData] = useState({});

const handleChange = (event) => {
    const name = event.target.name;
    const value = event.target.value?.trim();

    setError({ ...error, [name]: null });
    setData({ ...data, [name]: value });
}
```

Тогда в await register можно подкладывать `data`, а ошибки закидывать в `setError` похожей на конструкцию в handleChange

2024-11-15 14:24 UTC, sh4rkizz commented on react-chat/src/components/Register/Register.jsx
> +    };
Аналогичное упрощение можно применить в профиле

2024-11-16 09:26 UTC, sh4rkizz approved these changes
lgtm

2024-11-19 15:09 UTC, merged

2024-11-19 15:10 UTC, martinkomitsky commented
10