dz9
lada-nikiforova/2024-2-VK-EDU-Frontend-L-Nikiforova pull request #9
Opened 2024-11-26 12:18 UTC by lada-nikiforova

# Домашнее задание №9

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Добавлена redux
*
*

2024-11-30 13:48 UTC, sh4rkizz commented
Код выглядит высококлассно, но есть вот такая ошибочка на странице со списком чатов

```
TypeError: can't access property "text", n.last_message is null
```

2024-11-30 21:11 UTC, sh4rkizz requested changes

2024-11-30 21:11 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
>  import { activeChatId, activePerson } from '../../constant';
Сейчас кликабельная область для загрузки фото довольно маленькая [нужно попасть в label]
Давай расширим на всю площадь кнопки

<img width="225" alt="изображение" src="https://github.com/user-attachments/assets/411671e6-e5c7-44ce-851f-997a19681b30">

2024-11-30 21:11 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
>  import { activeChatId, activePerson } from '../../constant';
Давай поправим фотки - они какие-то некруглые

<img width="113" alt="изображение" src="https://github.com/user-attachments/assets/8a732b7a-95ee-4c29-8427-7102b5d2eb4a">

2024-11-30 21:11 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
>  import { activeChatId, activePerson } from '../../constant';
Предлагаю, когда нет фотографии [пользователь ничего не загрузил]
вместо img - span [круглый]
его контент - первая буква имени + первая буква фамилии [в верхнем регистре]

<img width="343" alt="изображение" src="https://github.com/user-attachments/assets/72ada3d2-2164-4a01-a6fc-efba2585a73a">

Примерно вот таким образом 

![telegram-cloud-photo-size-2-5357159334922021002-m](https://github.com/user-attachments/assets/da773de0-7686-4d9c-8941-943b16ec8bbd)

2024-11-30 21:11 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
>  import { activeChatId, activePerson } from '../../constant';
Вот эта модалка не закрывается на крестик или клик вне ее
Поправь пожалуйста

<img width="707" alt="изображение" src="https://github.com/user-attachments/assets/8dcd8afd-cc1c-406b-a81d-9d5ae5656e6b">

2024-11-30 21:11 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
>  import { activeChatId, activePerson } from '../../constant';
Предлагаю добавить лоадер

когда находишься в чате A, выходишь назад, переходишь к чату Б
на долю секунды видишь сообщения из чата А, после чего они ререндерятся

2024-11-30 21:11 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
>  import { activeChatId, activePerson } from '../../constant';
Ну и в целом на каждой странице хорошо бы добавить лоадер

Бекенд отдает данные не сразу, нужно показать пользователю, что это не у него пусто в полях
А что сервер еще не отгрузил ответ

Касается страницы профиля, списка чатов, сообщений чата

Базово везде применяется два подхода
\- скелетон
\- крутилка

2024-12-03 20:48 UTC, sh4rkizz approved these changes
очень-очень круто!
lgtm

2024-12-06 22:16 UTC, HaseProgram commented
Лайк! Аппрув! 7

2024-12-06 22:16 UTC, merged